---
title: "timeOmics: Seasonality Data"
author: "Antoine Bodein"
output: html_document
---

```{r echo=F}
knitr::opts_chunk$set(warnig=FALSE, 
                      fig.align = "center",
                      message = F)
```


```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(timeOmics)
library(lubridate)
library(lmms)

rm(list=ls())

load("./Multi_Omics_Seasonal.RData")
```

# 0. DATA CLEANING

```{r cleaning}
Gut_annotation_colData <- Gut_annotation_colData %>%
    mutate(YMD = lubridate::dmy(IRIS)) %>%
    mutate(Date = IRIS) %>%
    mutate(Time = yday(YMD)) %>%
    mutate(omics = "Gut") %>% dplyr::select(-Date, -BMI, -IRIS)

list_lab <- list("RNA" = RNA_annotation_colData,
                 "Metabo" = Metabolomics_annotation_colData,
                 #"Gut" =Gut_annotation_colData,
                 "Clinical" = Clinical_labs_annotation_colData)

list_lab_df <- imap_dfr(list_lab, ~{.x %>% 
        mutate("omics" = .y) %>% 
        mutate(YMD = lubridate::ymd(as.Date(Date))) %>% 
        dplyr::select(-Date)
})

IRIS_BMI <- list_lab_df[c(1:3)] %>% unique() 
IRIS_only <- IRIS_BMI %>% dplyr::select(-BMI) %>% unique %>% filter(!is.na(IRIS), !is.na(SubjectID)) %>%
    unique
IRIS_1 <- IRIS_only %>% group_by(SubjectID) %>%
    dplyr::summarise(N = n()) %>%
    filter(N == 1) %>% pull(SubjectID) %>% as.character()
IRIS_only <- IRIS_only %>% filter(SubjectID %in% IRIS_1)
```

# 1. DATA PREPARATION
```{r data_prep}
# GUT
###########################
GUT_sample <- Gut_annotation_colData %>% 
    mutate(Year = ifelse(year(YMD) < 2000, year(YMD) +2000, year(YMD))) %>%
    left_join(IRIS_only) %>%
    mutate(SampleID = paste0(SubjectID, "_", Time, "_",  Year, "_", IRIS, "_", rownames(.)))

GUT <- gut_df_Data
rownames(GUT) <- GUT_sample$SampleID

# CLINICAL
###########################
CLINICAL_sample <- Clinical_labs_annotation_colData %>% 
    mutate(Year = ifelse(year(Date) < 2000, year(Date) +2000, year(Date))) %>%
    left_join(IRIS_only) %>%
    mutate(SampleID = paste0(SubjectID, "_", Time, "_", Year, "_", IRIS, "_", rownames(.))) 

CLINICAL <- clinical_labs_Data
rownames(CLINICAL) <- CLINICAL_sample$SampleID
index.na <- CLINICAL %>% lapply(function(x) is.na(x) %>% sum) %>% unlist
CLINICAL <- CLINICAL[index.na<=11] %>% na.omit

# RNA
###########################
RNA_sample <- RNA_annotation_colData %>% 
    mutate(Year = ifelse(year(Date) < 2000, year(Date) +2000, year(Date))) %>%
    left_join(IRIS_only) %>%
    mutate(SampleID = paste0(SubjectID, "_", Time, "_", Year, "_", IRIS, "_", rownames(.))) 

index.NA <- (!is.na(RNA_annotation_colData$Time) & !is.na(RNA_annotation_colData$Time))
RNA_sample <- RNA_sample[index.NA,]
RNA <- RNA_df_Data[index.NA,]
rownames(RNA) <- RNA_sample$SampleID

# NOSE
###########################
Nasal_sample <- Nasal_annotation_colData %>% 
    mutate(Year = ifelse(year(Date) < 2000, year(Date) +2000, year(Date))) %>%
    left_join(IRIS_only) %>%
    mutate(SampleID = paste0(SubjectID, "_", Time, "_",  Year, "_", IRIS, "_", rownames(.)))

NASAL <- Nasal_df_Data
rownames(NASAL) <- Nasal_sample$SampleID

# PROTEIN
###########################
PROT_sample <- Proteomics_annotation_colData %>% 
    mutate(Year = ifelse(year(Date) < 2000, year(Date) +2000, year(Date))) %>%
    left_join(IRIS_only) %>%
    mutate(SampleID = paste0(SubjectID, "_", Time, "_",  Year, "_", IRIS, "_", rownames(.)))

PROT <- Proteomics_df_Data
rownames(PROT) <- PROT_sample$SampleID

# METABOLITE
###########################
METAB_sample <- Metabolomics_annotation_colData %>% 
    mutate(Year = ifelse(year(Date) < 2000, year(Date) +2000, year(Date))) %>%
    left_join(IRIS_only) %>%
    mutate(SampleID = paste0(SubjectID, "_", Time, "_",  Year, "_", IRIS, "_", rownames(.)))

METAB <- Metabolomics_df_Data
rownames(METAB) <- METAB_sample$SampleID

# CYTOKINE
###########################
CYTO_sample <- Cytokines_annotation_colData %>% 
    mutate(Year = ifelse(year(Date) < 2000, year(Date) +2000, year(Date))) %>%
    left_join(IRIS_only) %>%
    mutate(SampleID = paste0(SubjectID, "_", Time, "_",  Year, "_", IRIS, "_", rownames(.)))

CYTO <- Cytokines_df_Data
rownames(CYTO) <- CYTO_sample$SampleID

############################

# DATA: only RNA/CLINICAL/GUT/METAB
# split by IR/IS
DATA <- list("RNA.IR" = RNA[str_split(rownames(RNA),"_") %>% map_chr(~.x[[4]]) == "IR",],
             "GUT.IR" = GUT[str_split(rownames(GUT),"_") %>% map_chr(~.x[[4]]) == "IR",],
             
             "CLINICAL.IR" = CLINICAL[str_split(rownames(CLINICAL),"_") %>% map_chr(~.x[[4]]) == "IR",],
             "RNA.IS" = RNA[str_split(rownames(RNA),"_") %>% map_chr(~.x[[4]]) == "IS",],
             
             "GUT.IS" = GUT[str_split(rownames(GUT),"_") %>% map_chr(~.x[[4]]) == "IS",],
             "CLINICAL.IS" = CLINICAL[str_split(rownames(CLINICAL),"_") %>% map_chr(~.x[[4]]) == "IS",],
             
             "METAB.IR" = METAB[str_split(rownames(METAB),"_") %>% map_chr(~.x[[4]]) == "IR",],
             "METAB.IS" = METAB[str_split(rownames(METAB),"_") %>% map_chr(~.x[[4]]) == "IS",]
) 

COMBINED <- list("RNA" = RNA, CLINICAL = CLINICAL, GUT = GUT, METAB = METAB)
save(DATA, file = "RAW_DATA.RDA")
############################################################
```

```{r}
stat_raw_data <- lapply(list(RNA=RNA, GUT=GUT, METAB=METAB, CLINICAL=CLINICAL), dim) %>%
    as.data.frame() %>% t %>% as.data.frame() %>%
    setNames(c("sample", "feature"))
lapply(list(RNA=RNA, GUT=GUT, METAB=METAB, CLINICAL=CLINICAL), function(x){
    rownames(x) %>% str_remove("_.*") %>% unique %>% length()}) %>% 
    as.data.frame() %>%  t %>% as.data.frame() %>% setNames("uniqueID") %>%
    rownames_to_column("omic") %>%
    left_join(stat_raw_data %>% rownames_to_column("omic")) %>% column_to_rownames("omic") %>% t %>%
    as.data.frame() %>% knitr::kable()
```

# 2. DATA FILTERING

```{r data_filtering, fig.align="center"}
# 1. coef. of var
cv.data <- lapply(DATA, function(X){
    unlist(lapply(as.data.frame(X), 
                  function(x) abs(sd(x, na.rm = TRUE)/mean(x, na.rm= TRUE))))
})

fc.data <- list("RNA.IR"= 1.5, "RNA.IS"=1.5,
                "CLINICAL.IR"=0.2, "CLINICAL.IS"=0.2,
                "GUT.IR"=2, "GUT.IS"=2,
                "METAB.IR"=2 , "METAB.IS"=2)
    
par(mfrow = c(2,4))
for(i in c("RNA.IR","CLINICAL.IR", "GUT.IR", "METAB.IR", "RNA.IS","CLINICAL.IS", "GUT.IS", "METAB.IS")){
    hist(cv.data[[i]], breaks = 20, main =i)
    abline(v = fc.data[[i]], col = "red")
    legend("topright", legend = paste0("FC = ",fc.data[[i]]), col = "red", lty = 1) 
}
par(mfrow = c(1,1))


# 2. Remove low cv features
remove.low.cv <- function(X, cutoff = 0.5){
    # var.coef
    cv <- unlist(lapply(as.data.frame(X), 
                        function(x) abs(sd(x, na.rm = TRUE)/mean(x, na.rm= TRUE))))
    return(X[,cv > cutoff])
}

DATA.filtered <- list("RNA.IR" = remove.low.cv(DATA$RNA.IR, 1.5),
                      "RNA.IS" = remove.low.cv(DATA$RNA.IS, 1.5),
                      "GUT.IR" = remove.low.cv(DATA$GUT.IR, 2),
                      "GUT.IS" = remove.low.cv(DATA$GUT.IS, 2),
                      "CLINICAL.IR" = remove.low.cv(DATA$CLINICAL.IR, 0.2),
                      "CLINICAL.IS" = remove.low.cv(DATA$CLINICAL.IS, 0.2),
                      "METAB.IR" = remove.low.cv(DATA$METAB.IR, 2),
                      "METAB.IS" = remove.low.cv(DATA$METAB.IS, 2))
lapply(DATA.filtered, dim)

# 3. scale filtered value (log, scale, CLR)

# scale for OTU
norm_OTU <- function(DF, AR = F){
    DF <- DF + 0.0001
    
    data.TSS.clr = mixOmics::logratio.transfo(DF, logratio = 'CLR')
    
    # reconstrcuct dataframe
    data.good <- as.data.frame(matrix(ncol = ncol(data.TSS.clr), 
                                      nrow = nrow( data.TSS.clr)))
    rownames(data.good) <- rownames(data.TSS.clr)
    colnames(data.good) <- colnames(data.TSS.clr)
    for( i in c(1:nrow(data.TSS.clr))){
        for( j in c(1:ncol(data.TSS.clr))){
            data.good[i,j] <- data.TSS.clr[i,j]
        }
    }
    return(data.good)
}


DATA.filtered.scale <- list(
    "RNA.IR" = log(DATA.filtered$RNA.IR + 1) %>% scale,
    "RNA.IS" = log(DATA.filtered$RNA.IS + 1) %>% scale,
    
    "CLINICAL.IR" = log(DATA.filtered$CLINICAL.IR +1)%>% scale,
    "CLINICAL.IS" = log(DATA.filtered$CLINICAL.IS +1)%>% scale,
    
    "GUT.IR" = norm_OTU(DATA.filtered$GUT.IR),
    "GUT.IS" = norm_OTU(DATA.filtered$GUT.IS),
    
    "METAB.IR" = log(DATA.filtered$METAB.IR +1)%>% scale,
    "METAB.IS" = log(DATA.filtered$METAB.IS +1)%>% scale
)

lapply(DATA.filtered, dim) %>%
    as.data.frame() %>% t %>% as.data.frame() %>%
    setNames(c("sample", "feature")) %>%
    rownames_to_column("OMIC") %>%
    mutate(IRIS = str_extract(OMIC,"..$"), OMIC = str_remove(OMIC, "...$"))  %>%
    gather(meta, value, -c(OMIC, IRIS)) %>%
    spread(OMIC, value) %>% arrange(IRIS) %>%
    dplyr::select(IRIS, meta, RNA, GUT, METAB, CLINICAL)

save(DATA.filtered.scale, DATA.filtered, file = "./DATA_FILTERED.RDA")
############################################################
```

```{r}
fc.data.combined <- list("RNA"= 1.5, 
                "CLINICAL"=0.2,
                "GUT"=2,
                "METAB"=2)
cv.data.combined <- lapply(COMBINED, function(X){
    unlist(lapply(as.data.frame(X), 
                  function(x) abs(sd(x, na.rm = TRUE)/mean(x, na.rm= TRUE))))
})
fc.color <- list("RNA"= color.mixo(4), 
                "CLINICAL"=color.mixo(1),
                "GUT"=color.mixo(2),
                "METAB"=color.mixo(3))

par(mfrow = c(2,2))
for(i in c("RNA","CLINICAL", "GUT", "METAB")){
    hist(cv.data.combined[[i]], breaks = 20, main =i, xlab = paste0("Var. Coef. (", i, ")"), 
         col = fc.color[[i]])
    abline(v = fc.data.combined[[i]], col = "red")
    legend("topright", legend = paste0("CV = ",fc.data.combined[[i]]), col = "red", lty = 1) 
}
par(mfrow = c(1,1))
```

# 3. MODELLING

```{r modelling, cache=TRUE}
lmms.func <- function(X, mode = "p-spline"){
    time <- rownames(X) %>% str_split("_") %>% map_chr(~.x[[2]]) %>% as.numeric()
    lmms.output <- lmms::lmmSpline(data = X, time = time,
                                   sampleID = rownames(X), deri = FALSE,
                                   basis = mode, numCores = 4, 
                                   keepModels = TRUE)
    return(lmms.output)
}

# only one ID/Year
ID_u <- "ZLZNCLZ"
Year_u <- 2015

# just a filter to get only the selected ID/Year
DATA.GOOD <- imap_dfr(DATA.filtered.scale, ~{
    .x %>% as.data.frame() %>% rownames_to_column("sample") %>%
        gather(feature, value, -sample) %>%
        mutate(ID = str_split(sample, "_") %>% map_chr(~.x[[1]])) %>%
        mutate(year = str_split(sample, "_") %>% map_chr(~.x[[3]])) %>%
        mutate(OMIC = str_remove(.y, "...$")) %>%
        filter(ID == ID_u, year == Year_u)
    }) %>% split(.$OMIC) %>%
    purrr::map(~{
        .x %>% 
            dplyr::select(sample, feature, value) %>%
            spread(feature, value) %>% 
            column_to_rownames("sample")
    })


MODELLED <- lapply(DATA.GOOD, function(x) lmms.func(x))
```

```{r}
MODELLED %>% lapply(function(x)x@predSpline %>% dim) %>%
    as.data.frame() %>% t %>% as.data.frame() %>%
    setNames(c("sample", "feature")) %>% t %>%as.data.frame() %>%
    dplyr::select(RNA, GUT, METAB, CLINICAL)

MODELLED %>% imap_dfr(~.x@modelsUsed %>% table %>% as.data.frame  %>%
                        column_to_rownames(".") %>% t %>% as.data.frame %>% 
                        mutate(omic = .y)) %>% column_to_rownames('omic') %>% t %>%
    as.data.frame() %>% dplyr::select(RNA, GUT, METAB, CLINICAL)
```

# 4. STRAIGHT LINE FILTERING

```{r lmms_filter}
filterlmms.func <- function(modelled.data, lmms.output){
    time = modelled.data %>% rownames() %>% str_split("_") %>% map_chr(~.x[[2]]) %>% as.numeric()
    #time = rownames(modelled.data) %>% as.numeric()
    filter.res <- lmms.filter.lines(data = modelled.data,
                                    lmms.obj = lmms.output, time = time,
                                    homoskedasticity.cutoff=0.05)$filtered
}

FILTER <- lapply(names(DATA.GOOD), function(x) filterlmms.func(modelled.data = DATA.GOOD[[x]], lmms.output = MODELLED[[x]]))
names(FILTER) <- names(MODELLED)

FILTER %>% lapply(dim) %>%
      as.data.frame() %>% t %>% as.data.frame() %>%
    setNames(c("sample", "feature")) %>%
     t %>%as.data.frame() %>%
    dplyr::select(RNA, GUT, METAB, CLINICAL)
    
FINAL.FILTER <- FILTER[c("CLINICAL", "GUT", "METAB", "RNA")]
rownames(FINAL.FILTER[["GUT"]]) <- rownames(FINAL.FILTER[["RNA"]]) # change 86 par 85

save(FINAL.FILTER, MODELLED, DATA.GOOD, file = "./LMMS.RDA")
```

# 5. MULTI-OMICS CLUSTERING

```{r clustering_ncomp, cache=TRUE}
block.res <- block.pls(FINAL.FILTER, indY = 1, ncomp = 5)
getNcomp.res <- getNcomp(block.res, X = FINAL.FILTER, indY = 1)
```

```{r clustering_block, fig.align="center"}
plot(getNcomp.res)

# ncomp = 2
block.res <- block.pls(FINAL.FILTER, indY = 1, ncomp = 1, scale =FALSE) 

plotLong(object = block.res, title = "Block-PLS Clusters, scale = TRUE", legend = TRUE)

getCluster(block.res) %>% group_by(block, cluster) %>% summarise(N = n()) %>%
    spread(block, N) %>%
        dplyr::select(cluster, RNA, GUT, METAB, CLINICAL)
```


```{r clustering_tuning, cache=TRUE}
# elagage
test.list.keepX <- list(
    "CLINICAL" = seq(2,8,by=1),
    "GUT" = seq(2,10,by=1),
    "METAB" = seq(2,9,by=1),
    "RNA" = seq(10,50,by=2)
)

tune.block.res <- tuneCluster.block.spls(X= FINAL.FILTER, indY = 1,
                                         test.list.keepX=test.list.keepX, 
                                         scale=FALSE, 
                                         mode = "canonical", ncomp = 1)
```
```{r clustering_sparse_final, fig.align="center"}
tune.block.res$choice.keepX 
final.block <- block.spls(FINAL.FILTER, indY = 1, ncomp = 1, scale =FALSE, 
                          keepX = tune.block.res$choice.keepX) 
plotLong(final.block, legend = TRUE)

getCluster(final.block) %>% group_by(block, cluster) %>% summarise(N = n()) %>%
    spread(block, N) %>%
        dplyr::select(cluster, RNA, GUT, METAB, CLINICAL)

library("openxlsx")
  cluster_comp <- getCluster(final.block) %>% dplyr::select(molecule, block, cluster, comp, contribution) %>% 
  mutate(cluster = ifelse(cluster == -1, "Cluster 1", "Cluster 2")) %>%
  split(.$cluster)
write.xlsx(cluster_comp, file = "cluster_composition.xlsx")
```

# 6. CLUSTER VALIDATION WITH PROPORTIONNALITY DISTANCE

```{r propr, , fig.align="center"}
res <- proportionality(final.block)

pval.propr <- res$pvalue
knitr::kable(pval.propr)

plot(res)
save(res, final.block, file ="./FINAL_PROPR.RDA")
```


# 7. Enrichment analysis

```{r interpretation, include=F}
getCluster(block.res) %>% group_by(block, cluster) 
pltlong.res <- plotLong(object = block.res, title = "Block-PLS Clusters, scale = TRUE", legend = TRUE)

ggplot(pltlong.res, aes(x = time, y = value, color = cluster)) + geom_smooth(method = "loess")
```


```{r gprofiler}
# genes enrichment
library(gprofiler2)
tmp <- getCluster(block.res)
genes.c1 <- tmp %>% filter(block == "RNA", cluster == -1) %>% pull(molecule)
genes.c2 <- tmp %>% filter(block == "RNA", cluster == 1) %>% pull(molecule)

gost.c1 <- gost(query = genes.c1, organism = "hsapiens")
gost.c2 <- gost(query = genes.c2, organism = "hsapiens")

multi_gost <- gost(query = list("Cluster_1"=genes.c1,"Cluster_2"= genes.c2), organism = "hsapiens", multi_query = TRUE, source = c("GO", "REAC", "WP"))

head(multi_gost$result)

p <- gostplot(multi_gost, interactive = FALSE, capped = FALSE)
p <- gostplot(multi_gost, interactive = TRUE, capped = FALSE)

# pub.res <- publish_gosttable(multi_gost,
#                   #highlight_terms = multi_gost$result,
#                         use_colors = TRUE, 
#                         show_columns = c("source", "term_name", "term_size"),
#                         filename = NULL)

write_csv(as.data.frame(genes.c1), file = "./c1_genes.txt", col_names = FALSE)
write_csv(as.data.frame(genes.c2), file = "./c2_genes.txt", col_names = FALSE)

 multi_gost$result %>% filter(term_id %in% intersect(gost.c1$result$term_id, gost.c2$result$term_id))

# sparse
########################################################################
tmp <- getCluster(final.block)
sparse.genes.c1 <- tmp %>% filter(block == "RNA", cluster == -1) %>% pull(molecule)
sparse.genes.c2 <- tmp %>% filter(block == "RNA", cluster == 1) %>% pull(molecule)

multi_gost_sparse <- gost(query = list("Cluster_1"=sparse.genes.c1,"Cluster_2"= sparse.genes.c2), organism = "hsapiens", multi_query = TRUE)

p <- gostplot(multi_gost_sparse, interactive = FALSE, capped = FALSE)

write_csv(as.data.frame(sparse.genes.c1), file = "./c1_genes_sparse.txt", col_names = FALSE)
#write_csv(as.data.frame(sparse.genes.c2), file = "./c2_genes.txt", col_names = FALSE)


# final gostplot + spars gosttable
p <- gostplot(multi_gost, interactive = FALSE, capped = FALSE)
publish_gostplot(p, filename = "./gostplot.png")
publish_gostplot(p,  highlight_terms = intersect(multi_gost_sparse$result$term_id, multi_gost$result$term_id), filename = "./gostplot_tab.png")

# shared terms
 multi_gost$result %>% filter(term_id %in% intersect(multi_gost_sparse$result$term_id, multi_gost$result$term_id))

 
library("openxlsx")
gost_res <- list("Cluster 1" = gost.c1$result,
                     "Cluster 2" = gost.c2$result,
                     "Sparse Cluster 1" = multi_gost_sparse$result)
  
write.xlsx(gost_res, file = "cluster_gene_enrichment.xlsx")
```

```{r, include = FALSE}
library(DOSE)

library(org.Hs.eg.db)
hs <- org.Hs.eg.db

genes.c1.entrezID <- select(hs, keys = genes.c1, columns = c("ENTREZID", "SYMBOL"),
       keytype = "SYMBOL") %>% pull(ENTREZID)

enrichDO.c1 <- enrichDO(gene = genes.c1.entrezID)

genes.c2.entrezID <- select(hs, keys = genes.c2, columns = c("ENTREZID", "SYMBOL"),
       keytype = "SYMBOL") %>% pull(ENTREZID)

enrichDO.c2 <- enrichDO(gene = genes.c2.entrezID)
head(enrichDO.c2)
```

```{r medlineRanke}
medline_c1 <- read_tsv("./medlineranker_c1_genes.tsv")
medline_c2 <- read_tsv("./medlineranker_c2_genes.tsv") 
medline_c1_sparse <- read_tsv("./medlineranker_c1_sparse_gene")

#lapply(medlineR_res, function(x) x %>% filter(!str_detect(Disease, "Neoplasms")))
# medlineR_res.terms <- lapply(medlineR_res, function(x) x$Disease)

# intersect(medlineR_res.terms$`Cluster 1`, medlineR_res.terms$`Cluster 2`)
# intersect(medlineR_res.terms$`Cluster 1`, medlineR_res.terms$`Sparse Cluster 1`)
# intersect(medlineR_res.terms$`Cluster 2`, medlineR_res.terms$`Sparse Cluster 1`)

library("openxlsx")
medlineR_res <- list("Cluster 1" = medline_c1, 
                     "Cluster 2" = medline_c2,
                     "Sparse Cluster 1" = medline_c1_sparse)
write.xlsx(medlineR_res, file = "cluster_disease_enrichment.xlsx")
```

```{r}
# OTU
getCluster(block.res) %>% filter(block == "GUT")
getCluster(final.block) %>% filter(block == "GUT")

# 
getCluster(block.res) %>% filter(block == "CLINICAL") %>% arrange(cluster)
getCluster(final.block) %>% filter(block == "CLINICAL")

```


```{r, echo=FALSE, include = FALSE}
png(filename = "season_hist.png", width = 3000, height = 2000, res = 300)
plot.names <- list("RNA"="RNA",
                  "CLINICAL"= "Clinical", 
                "GUT"="OTU","METAB"="Metabolites")
par(mfrow = c(2,2))
for(i in c("RNA","CLINICAL", "GUT", "METAB")){
    hist(cv.data.combined[[i]], breaks = 20, main =plot.names[[i]], xlab = paste0("Var. Coef. (", plot.names[[i]], ")"), 
         col = fc.color[[i]])
    abline(v = fc.data.combined[[i]], col = "red")
    legend("topright", legend = paste0("CV = ",fc.data.combined[[i]]), col = "red", lty = 1) 
}
par(mfrow = c(1,1))
dev.off()

png(filename = "season_ncomp.png", width = 2000, height = 1000, res = 300)
plot(getNcomp.res)
dev.off()

png(filename = "season_cluster.png", width = 2000, height = 1500, res = 300)
plotLong(object = block.res, title = "(A.) Block-PLS Clusters, scale = TRUE", legend.title = "Omics",
         X.label = "Times (days)", Y.label = "Scaled Intensity / Abundance")
dev.off()

tmp <- plotLong(object = final.block, title = "(B.) sparse Block-sPLS Clusters, scale = TRUE", legend = TRUE, legend.title = "Omics") %>%
  mutate(block = plyr::revalue(block, c("CLINICAL"="Clinical", "GUT"= "OTU", "RNA"="RNA", "METAB"="Metabolites")))
png(filename = "season_sparse_cluster.png", width = 2000, height = 1500, res = 300)
ggplot(tmp, aes(x = time, y = value, group = molecule)) + 
        geom_line(aes(color = block)) + facet_grid(contribution ~ 
        comp, scales = "free") + scale_color_manual(values = mixOmics::color.mixo(1:4)) + 
        theme_bw()+
        labs(color = "Omics", x = "Times (days)", y ="Scaled Intensity / Abundance")  +
  ggtitle("(B.) sparse Block-sPLS Clusters, scale = TRUE")
dev.off()


png(filename = "season_propr.png", width = 2000, height = 1000, res = 300)
res$propr.distance.w.cluster %>% mutate(cluster1 = plyr::revalue(cluster1, c("1" = "Clutser 1", "-1"="Cluster 2")), cluster2 = plyr::revalue(cluster2, c("1" = "Clutser 1", "-1"="Cluster 2"))) %>%
ggplot2::ggplot(aes(x = as.factor(cluster1), 
        y = value, col = insideout)) + geom_boxplot() + theme_bw() + 
        xlab("Cluster ID") + ylab("Proportionality distance") + 
        labs(color = "Proportionality distance") 
dev.off()
```

